/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ece651.sp22.xg73.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

public class App {

  private TextPlayer p1;
  private TextPlayer p2;

  public App(TextPlayer p1, TextPlayer p2) {
    this.p1 = p1;
    this.p2 = p2;
  }

  public void doPlacementPhase() throws IOException {
    this.p1.doPlacementPhase();
    this.p2.doPlacementPhase();
  }

  public static void main(String[] args) throws IOException {
    Board<Character> b1 = new BattleShipBoard<Character>(10, 20, 'X');
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20, 'X');
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    V1ShipFactory factory = new V1ShipFactory();
    TextPlayer p1 = new TextPlayer("A", b1, input, System.out, factory);
    TextPlayer p2 = new TextPlayer("B", b2, input, System.out, factory);
    App a = new App(p1, p2);
    a.doPlacementPhase();
  }
}
